#!/usr/bin/env bash

#
# This script executes the Beeline client
# inside the edge container
#

docker container exec -it \
    --user alice  \
    edge \
        bash -l -c 'beeline -u $HIVE2_URL -n $USER -p bogus'