#!/usr/bin/env bash

#
# This script starts the Cloudera Hadoop cluster
#

readonly selfname=$(basename "$0")
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

source $selfdir/functions
parse_args $*


# Compose the cluster of services
docker-compose \
    --project-name $project_name \
    --file $compose_file \
    up --detach
