#!/usr/bin/env bash

#
# This script starts the Cloudera Hadoop cluster
#


# Compute the path to directory that contains this script
readonly selfname=$(basename "$0")
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"


function print_usage {
cat <<CAT
Usage:    $selfname --version <version> [--target <target> ] [ --auth <auth>] [ --sasl ] [ --tls ]
CAT
}


if ! [ -x "$(command -v sshpass)" ]; then
cat <<CAT
FATAL: sshpass not found!

You can install the missing tool as follows.
- macos
    brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb
- linux
    yum install sshpass
    apt-get install sshpass
CAT
exit 1
fi


while [[ $# -gt 0 ]]; do
key="$1"
case $key in
    --help)
        print_usage
        exit 0
    ;;
    --version)
        version="$2"
        shift; shift
      ;;
    --target)
        target="$2"
        case $target in
          /*) target=$target;;
           *) target=$PWD/$target;;
        esac
        shift; shift
      ;;
    --auth)
        auth="$2"
        shift; shift
      ;;
    --sasl)
        sasl_protection="privacy"
        shift
      ;;
    --tls)
        tls_encryption="true"
        shift
      ;;
    *)
        shift
      ;;
esac
done


case ${version} in
'5.4.2'|'5.16.1'|'6.0.1')
;;
*)
cat <<CAT
Error: missing or unsupported --version argument
You're required to pass one of the following:
  - 5.4.2
  - 5.16.1
  - 6.0.1
CAT
exit -1
;;
esac


case ${auth} in
'simple'|'kerberos')
;;
*)
cat <<CAT
Error: missing or unsupported --auth argument
You're required to pass one of the following:
  - simple
  - kerberos
CAT
exit -1
;;
esac


export registry="registry.alpinedata.tech"
export repository="pangiolet/cloudera"
export version="${version}"
export hadoop_auth="${auth}"
export target="${target:-$(pwd)/target}/cloudera"
export sasl_protection="${sasl_protection:-authentication}"
export tls_encryption="${tls_encryption:-false}"


cat <<CAT
-----------------------------------
Starting Cloudera Hadoop with
  - version          $version
  - hadoop_auth      $hadoop_auth
  - sasl_protection  $sasl_protection
  - tls_encryption   $tls_encryption
  - target           $target

CAT

docker-compose \
    --project-name cdh-$version \
    --file $selfdir/docker-compose.yml \
    up --detach #> /dev/null 2>&1


#echo "Configuring SSH  ... "
#sleep 32
#ssh-keygen -R [edge.docker.net]:2222
#ssh-keyscan -p 2222 edge.docker.net >> ~/.ssh/known_hosts
#sshpass -p "alice" ssh-copy-id -f -p 2222 "alice@edge.docker.net"
#
#
#echo "Configuring Hadoop client ... "
#sleep 32
#$selfdir/client/configure --target $target
#exit 0
