#!/usr/bin/env bash

#
# This script stops the Cloudera Hadoop cluster
#

# Compute the path to directory that contains this script
readonly selfname=$(basename "$0")
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

printf "%-24s ... " "Stopping Cloudera Hadoop"
for container in datanode1 nodemanager1 resourcemanager namenode jobhistory hive edge kdc; do
  docker container stop ${container} > /dev/null 2>&1
done
docker container prune --force  > /dev/null 2>&1

printf "done\n"
echo "-----------------------------------"
