#!/usr/bin/env bash

#
# This script stops the Cloudera CDH5 cluster
#

readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

services="$*"
if [[ "${services}x" == "x" ]]; then
    services="hive nodemanager1 resourcemanager jobhistory datanode1 namenode kdc"
fi

echo "Stopping Cloudera CDH5"
for container in $services; do docker container stop $container; done
docker container prune --force
