#!/usr/bin/env bash

readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
readonly selfname=$(basename "$0")

readonly red="$(tput setaf 1)"
readonly green="$(tput setaf 2)"
readonly reset="$(tput setaf 7)"


function check_args {
  while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
      --version)
          version="$2"
          shift; shift
        ;;
      --jdk)
          jdk="$2"
          shift; shift
        ;;
      *)
        shift
      ;;
  esac
  done

  if [[ "${version}x" == "x" ]]; then cat <<CAT

${red}Error${reset}: missing --version argument
You're required to pass a specific Cloudera Hadoop version.
Try with one of the followings:
  --version ${green}5.4.2${reset}
  --version ${green}5.16.1${reset}
  --version ${green}6.0.1${reset}
  --version ${green}6.2.0${reset} 
CAT
  exit -1
  fi

  if [[ "${jdk}x" == "x" ]]; then cat <<CAT

${red}Error${reset}: missing --jdk
You are required to download the jdk-8u201-linux-x64.rpm
package from official Oracle website and to accept the
Oracle license terms.
CAT
    exit -1
  fi
}


function build_yum_image {
  echo '-------------------------------'
  echo 'Building Docker YUM image'
  echo '-------------------------------'
  docker image ls | grep yum  && docker image rm yum
  docker build --tag yum ${selfdir}
}


function build_repo {
  local provider=$1
  local repoid=$2

  dest="${selfdir}/repos/${provider}"
  mkdir -p $dest

  if [[ "${provider}" == "cloudera" ]]; then
    if [[ $repoid == cdh-5* ]]; then cat <<CAT > $dest/$repoid.repo
[$repoid]
name=Cloudera Hadoop $version
baseurl=https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/$version
gpgkey=https://archive.cloudera.com/cdh5/redhat/6/x86_64/cdh/RPM-GPG-KEY-cloudera
gpgcheck=1
CAT

    elif [[ $repoid == cdh-6* ]]; then cat <<CAT > $dest/$repoid.repo
[$repoid]
name=Cloudera Hadoop $version
baseurl=https://archive.cloudera.com/cdh6/$version/redhat6/yum/
gpgkey=https://archive.cloudera.com/cdh6/$version/redhat6/yum/RPM-GPG-KEY-cloudera
gpgcheck=1
CAT
    fi
    opts="--volume $dest/$repoid.repo:/etc/yum.repos.d/${provider}-$repoid.repo"
  fi

  docker container run \
    --rm $opts \
    --volume ${selfdir}/repos/build:/etc/yum/build \
    --volume ${selfdir}/repos:/repos \
    yum \
    bash -c "/etc/yum/build ${provider} $repoid; exit 0"
}


function copy_oracle_jdk {
  dest="$selfdir/repos/oracle"
  mkdir -p ${dest}

  echo "Copying $(basename $jdk)"
  yes | cp -rf ${jdk} ${dest}
  ln -snf $(basename ${jdk}) ${dest}/jdk-8.rpm
}




# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

check_args $*
copy_oracle_jdk
build_yum_image

#            provider      repoid
build_repo   centos-6.10   base
build_repo   centos-6.10   centosplus
build_repo   centos-6.10   extras
build_repo   centos-6.10   updates
build_repo   cloudera      cdh-${version}

exit 0
