#!/usr/bin/env bash

#
# Setup user accounts with proper ~/.bash_profile
#
chmod +x /etc/docker/setup
# --------------   user   group   domain
/etc/docker/setup  mapred  hadoop  docker.net


#
# Render configuration templates by replacing {{ PLACEHOLDER }}
# with corresponding shell environment variable values
#
chmod +x /etc/docker/render
/etc/docker/render  /etc/hadoop/conf/core-site.xml
/etc/docker/render  /etc/hadoop/conf/hdfs-site.xml
/etc/docker/render  /etc/hadoop/conf/mapred-site.xml


# Publish the Hadoop configuration through the /shared/conf directory
mkdir -p /shared/conf
rm -f  /shared/conf/mapred-site.xml

cp /etc/hadoop/conf/mapred-site.xml /shared/conf


#
# Make log directories
#
mkdir -p /var/log/hadoop-mapreduce
chown mapred:mapred /var/log/hadoop-mapreduce
chmod 755 /var/log/hadoop-mapreduce
# TODO ln -snf /dev/stdout /var/log/hadoop-mapreduce/hadoop-mapreduce-???-???.docker.net.log


# TODO https://www.cloudera.com/documentation/enterprise/5-15-x/topics/cdh_sg_users_groups_verify.html#topic_3_2_6


# Wait until namenode service is available
while ! echo exit | nc namenode.docker.net 8020; do sleep 10; done



# Start the Hadoop MapReduce JobHistory service
service hadoop-mapreduce-historyserver start


# Keep this container running
/etc/docker/idle
