#!/usr/bin/env bash

#
# This script destroys (removes) the Docker images for
# the containerized Cloudera Hadoop cluster
#

# Compute the path to directory that contains this script
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $selfdir/functions


function destroy {
  local image="$1"

  # Append the version tag (e.g. 'alpha2' or '1.0') of the Docker images
  local version="$cdh5_version-$image_patch"

  docker image rm ${repository}/${image}:${version}
  docker image rm ${registry}/${repository}/${image}:${version}
}


check_args $*
perform destroy
