#!/usr/bin/env bash

# Compute the path to directory that contains this script
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $selfdir/functions

readonly network="build.net"
readonly registry="registry.alpinedata.tech"
readonly repository="pangiolet/cloudera"



function rm {
  local image="$1"
  local version="${cloudera_version}"
  docker image rm ${repository}/${image}:${version}
  docker image rm ${registry}/${repository}/${image}:${version}
}


check_args $*
perform rm
