#!/usr/bin/env bash

readonly red="$(tput setaf 1)"
readonly green="$(tput setaf 2)"
readonly reset="$(tput setaf 7)"

readonly registry="registry.alpinedata.tech"
readonly repository="red/cdh"
readonly network="build.net"


function check_args {
  while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
      -v|--version)
          cdh_version="$2"
          shift; shift # past value
        ;;
      -p|--patch)
          image_patch="$2"
          shift; shift # past value
        ;;
      *)
        shift
      ;;
  esac
  done

  if [[ "${cdh_version}x" == "x" ]]; then cat <<CAT
${red}Error${reset}: missing --version argument
You're required to pass a specific Cloudera Hadoop version.
Try with one of the followings:
  --version ${green}5.4.2${reset}
  --version ${green}5.16.1${reset}
CAT
  exit -1
  fi
}


image_patch=${image_patch:-$(git describe --dirty)}


function perform {
  local action="${1}"
  ${action} base
  ${action}   kdc
  ${action}   hadoop-hdfs/namenode
  ${action}   hadoop-hdfs/datanode
  # ${action}   hadoop-mapred/jobhistory
  # ${action}   hadoop-yarn/resourcemanager
  # ${action}   hadoop-yarn/nodemanager
  # ${action}   hive
}
