#!/usr/bin/env bash

# readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
# readonly network="build.net"
# readonly registry="registry.alpinedata.tech"
# readonly repository="pangiolet/cloudera"


readonly red="$(tput setaf 1)"
readonly green="$(tput setaf 2)"
readonly reset="$(tput setaf 7)"


function check_args {
  while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
      -v|--version)
          cloudera_version="$2"
          shift
          shift # past value
        ;;
      *)
        shift
      ;;
  esac
  done

  if [[ "${cloudera_version}x" == "x" ]]; then cat <<CAT

${red}Error: missing --version argument${reset}

  You're required to pass a specific Cloudera Hadoop version to build.
  Try with one of the following
    - ${green}5.4.2${reset}
    - ${green}5.16.1${reset}
CAT
  exit -1
  fi
}


function perform {
  local action="${1}"
  ${action} base
  ${action}   kdc
  ${action}   hadoop-hdfs/namenode
  ${action}   hadoop-hdfs/datanode
  ${action}   hadoop-mapred/jobhistory
  ${action}   hadoop-yarn/resourcemanager
  ${action}   hadoop-yarn/nodemanager
  ${action}   hive
  # ${action}   master
  # ${action}   worker
  ${action}   edge
}
