#!/usr/bin/env bash

readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
readonly registry="registry.alpinedata.tech"
readonly repository="pangiolet/cloudera"


readonly red="$(tput setaf 1)"
readonly green="$(tput setaf 2)"
readonly reset="$(tput setaf 7)"


function check_requirements {
  while [[ $# -gt 0 ]]; do
  key="$1"
  case $key in
      --cloudera-version)
          cloudera_version="$2"
          shift
          shift # past value
        ;;
      *)
        shift
      ;;
  esac
  done

  if [[ "${cloudera_version}x" == "x" ]]; then cat <<CAT

${red}Error: missing --cloudera-version argument${reset}

  You're required to pass a specific Cloudera Hadoop version to build.
  Try with one of the following
    - ${green}5.4.2${reset}
    - ${green}5.16.1${reset}
CAT
  exit -1
  fi
}


function publish {
  local image="$1"
  local version="${cloudera_version}"
  docker push ${registry}/${repository}/${image}:${version}
}


function publish_images {
  publish base
  publish   kdc
  publish   hadoop/dfs/namenode
  publish   hadoop/dfs/datanode
  publish   hadoop/mapred/jobhistory
  publish   hadoop/yarn/resourcemanager
  publish   hadoop/yarn/nodemanager
  publish   hive
  publish   master
  publish   worker
  publish   edge
}



# function main {
check_requirements $*
# TODO docker_login
publish_images
