#!/usr/bin/env bash

#
# This script pulls the Docker images
# for the containerized Cloudera Hadoop cluster
# down from our GitLab image registry
#

# Compute the path to directory that contains this script
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $selfdir/functions


function pull {
  local image="$1"

  # Append the version tag (e.g. 'alpha1' or '1.0') of the Docker images
  local image_classifier="$(git describe)"
  local version="$cloudera_version-$image_classifier"

  docker image pull ${registry}/${repository}/${image}:${version}
}


check_args $*
perform pull
