#!/usr/bin/env bash

# Compute the path to directory that contains this script
readonly selfdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
source $selfdir/functions

readonly registry="registry.alpinedata.tech"
readonly repository="pangiolet/cloudera"




function push {
  local image="$1"
  local version="${cloudera_version}"
  docker image push ${registry}/${repository}/${image}:${version}
}

check_args $*
perform push
