#!/usr/bin/env bash

# Cleanup previous secrets
mkdir -p /shared/secrets
rm -Rf /shared/secrets/*


# Initialize the Kerberos realm database
chmod +x /etc/docker/init
/etc/docker/init


# Start the Kerberos KDC daemon
/usr/sbin/krb5kdc


# (Optional) Start Kerberos Admin daemon
# /usr/sbin/kadmind


# Keep this container running
/etc/docker/idle
